version: '3.8'

services:
  web:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - auth
      - posts
      - comments
      - marketing
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
  
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      - nats
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/auth
      - NATS_URL=nats://nats:4222
  
  posts:
    build:
      context: ./posts
      dockerfile: Dockerfile
    depends_on:
      - nats
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/posts
      - NATS_URL=nats://nats:4222
  
  comments:
    build:
      context: ./comments
      dockerfile: Dockerfile
    depends_on:
      - nats
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/comments
      - NATS_URL=nats://nats:4222
  
  marketing:
    build:
      context: ./marketing
      dockerfile: Dockerfile
    depends_on:
      - nats
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/marketing
      - NATS_URL=nats://nats:4222

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

volumes:
  mongodb_data:
