version: '3.8'

services:
  web:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - AUTH_SERVER_ADDR=backend:3001
      - POST_SERVER_ADDR=backend:3002
      - COMMENT_SERVER_ADDR=backend:3003
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
  
  common:
    build:
      context: ./common
      dockerfile: Dockerfile
  
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      - common
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
